// Action Types

// Countries
export const IS_LOADING_COUNTRIES = 'IS_LOADING_COUNTRIES';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const CLEAR_COUNTRIES = 'IS_LOADING_COUNTRIES';
// Cities
export const IS_LOADING_CITIES = 'IS_LOADING_CITIES';
export const SET_CITIES = 'SET_CITIES';
export const CLEAR_CITIES = 'IS_LOADING_CITIES';
// User Location
export const IS_LOADING_USER_LOCATION = 'IS_LOADING_USER_LOCATION';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const REMOVE_USER_LOCATION = 'REMOVE_USER_LOCATION';
// Weather Forecast
export const IS_LOADING_CURENT_LOCATION_FORECAST_DATA =
  'IS_LOADING_CURENT_LOCATION_FORECAST_DATA';
export const SET_CURENT_LOCATION_FORECAST_DATA =
  'SET_CURENT_LOCATION_FORECAST_DATA';
export const CLEAR_CURENT_LOCATION_FORECAST_DATA =
  'CLEAR_CURENT_LOCATION_FORECAST_DATA';
